services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./pages:/app/pages
      - ./styles:/app/styles
      - ./public:/app/public
      - ./scraper.js:/app/scraper.js
      - ./db.js:/app/db.js
      # Avoid mounting node_modules from host
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=1234
      - DB_NAME=pricescout
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./pages:/app/pages
      - ./styles:/app/styles
      - ./public:/app/public
      - ./next.config.js:/app/next.config.js
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=pricescout
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
  pgadmin-data: