services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3002:3000"  # Changed from 3000:3000 to avoid port conflict
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:1234@db:5432/pricescout
      - GOOGLE_CLIENT_ID=336594173141-bml3jeckmc40rd793k1h3c46j2ng5pdt.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - PORT=3000
    depends_on:
      - db
    volumes:
      - .:/app
    command: npm run dev:backend

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3001:3001"
    environment:
      - NEXTAUTH_URL=http://localhost:3001
      - GOOGLE_CLIENT_ID=336594173141-bml3jeckmc40rd793k1h3c46j2ng5pdt.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - NEXTAUTH_SECRET=your-secret
      - NEXT_PUBLIC_API_URL=http://localhost:3002
    depends_on:
      - app
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=pricescout
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  crawler:
    build:
      context: .
      dockerfile: Dockerfile.backend  # Reusing backend Dockerfile since it has Node.js
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:1234@db:5432/pricescout
    depends_on:
      - db
      - app  # Wait for the backend to be ready
    volumes:
      - .:/app
    command: npm run crawl  # Using the crawl script from package.json
    restart: on-failure
    # Add browser capabilities 
    cap_add:
      - SYS_ADMIN
    shm_size: 1gb

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pricescout.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgadmin-data: