version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3002:3000"  # Changed from 3000:3000 to avoid port conflict
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:1234@db:5432/pricescout
      - GOOGLE_CLIENT_ID=336594173141-bml3jeckmc40rd793k1h3c46j2ng5pdt.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - PORT=3000
    depends_on:
      - db
    volumes:
      - .:/app
    command: npm run dev:backend

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3001:3001"
    environment:
      - NEXTAUTH_URL=http://localhost:3001
      - GOOGLE_CLIENT_ID=your-google-client-id
      - GOOGLE_CLIENT_SECRET=your-google-client-secret
      - NEXTAUTH_SECRET=your-secret
      - NEXT_PUBLIC_API_URL=http://app:3000
    depends_on:
      - app
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules  # Preserve container-installed node_modules
    # Removed the "command" override to let Dockerfile CMD run

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=pricescout
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"